name: build
on:
   push:
     branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: show files
        run: ls -la
      - name: print branch
        run: echo "Building on ${{ Github.ref_name }}"       